# Generated by Django 5.0.3 on 2024-04-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.IntegerField(max_length=14)),
                ('age', models.IntegerField(max_length=3)),
                ('employee_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
