# Generated by Django 5.0.3 on 2024-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_employee_password_alter_employee_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('resident', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('area', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('description', models.TextField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='website_img/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='website_img/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='website_img/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='website_img/')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='website_img/')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
