# Generated by Django 5.0.3 on 2024-04-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('resident', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('area', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('description', models.TextField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='website_img/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='website_img/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='website_img/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='website_img/')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='website_img/')),
                ('entry_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
