# Generated by Django 5.0.3 on 2024-04-27 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rental_alter_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_no', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('client_nid', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.property')),
            ],
        ),
    ]
