# Generated by Django 5.0.3 on 2024-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_property_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='img1',
            new_name='image1',
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
