# Generated by Django 5.0.3 on 2024-05-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_img2_property_image2_remove_property_img3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='property_id',
        ),
    ]
