# Generated by Django 5.0.3 on 2024-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_transaction_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pid',
            field=models.CharField(max_length=50),
        ),
    ]
