# Generated by Django 5.0.3 on 2024-05-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_transaction_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.property'),
        ),
    ]
