# Generated by Django 5.0.3 on 2024-05-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_transaction_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='img5',
        ),
    ]
