# Generated by Django 5.0.3 on 2024-05-08 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_rename_client_client_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CLient_info',
            new_name='Client',
        ),
    ]
