# Generated by Django 5.0.3 on 2024-05-09 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_rename_img1_rental_image1_rename_img2_rental_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('total_paid', models.IntegerField(default=0)),
                ('due', models.IntegerField(default=0)),
                ('client_nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.client')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.transaction')),
            ],
        ),
    ]
