# Generated by Django 5.0.3 on 2024-05-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
