# Generated by Django 5.0.3 on 2024-05-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('total_paid', models.IntegerField()),
                ('due', models.IntegerField()),
                ('payment_status', models.CharField(max_length=50)),
                ('recent_trans', models.CharField(max_length=10, unique=True)),
                ('client_nid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.client')),
                ('pid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.property')),
            ],
        ),
    ]
