# Generated by Django 5.0.3 on 2024-05-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client_nid',
            field=models.CharField(max_length=50),
        ),
    ]
