# Generated by Django 5.0.3 on 2024-05-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_rename_property_id_payment_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
